"""update picth model to include votes

Revision ID: fd327f1087cd
Revises: 773d9d856353
Create Date: 2021-09-21 23:16:35.512608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd327f1087cd'
down_revision = '773d9d856353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('upvotes', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('downvotes', sa.Integer(), nullable=True))
    op.drop_index('ix_pitches_category', table_name='pitches')
    op.create_index(op.f('ix_pitches_category'), 'pitches', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pitches_category'), table_name='pitches')
    op.create_index('ix_pitches_category', 'pitches', ['category'], unique=False)
    op.drop_column('pitches', 'downvotes')
    op.drop_column('pitches', 'upvotes')
    # ### end Alembic commands ###
